# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Analysis(object):
    def setupUi(self, Analysis):
        Analysis.setObjectName("Analysis")
        Analysis.resize(962, 615)
        self.centralwidget = QtWidgets.QWidget(Analysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 991, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Table = QtWidgets.QWidget()
        self.tab_Table.setObjectName("tab_Table")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_Table)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 951, 541))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget.addTab(self.tab_Table, "")
        self.tab_XY = QtWidgets.QWidget()
        self.tab_XY.setObjectName("tab_XY")
        self.tabWidget.addTab(self.tab_XY, "")
        self.tab_Radar = QtWidgets.QWidget()
        self.tab_Radar.setObjectName("tab_Radar")
        self.tabWidget.addTab(self.tab_Radar, "")
        self.tab_Box = QtWidgets.QWidget()
        self.tab_Box.setObjectName("tab_Box")
        self.tabWidget.addTab(self.tab_Box, "")
        Analysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Analysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuNormalization = QtWidgets.QMenu(self.menuMenu)
        self.menuNormalization.setEnabled(False)
        self.menuNormalization.setObjectName("menuNormalization")
        self.menuPlots = QtWidgets.QMenu(self.menubar)
        self.menuPlots.setObjectName("menuPlots")
        Analysis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Analysis)
        self.statusbar.setObjectName("statusbar")
        Analysis.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(Analysis)
        self.actionOpen.setObjectName("actionOpen")
        self.actionMax_min = QtWidgets.QAction(Analysis)
        self.actionMax_min.setObjectName("actionMax_min")
        self.actionStandardization_M_0_S_1 = QtWidgets.QAction(Analysis)
        self.actionStandardization_M_0_S_1.setObjectName("actionStandardization_M_0_S_1")
        self.actionBaseline_Correction = QtWidgets.QAction(Analysis)
        self.actionBaseline_Correction.setObjectName("actionBaseline_Correction")
        self.actionPeak_Detection = QtWidgets.QAction(Analysis)
        self.actionPeak_Detection.setEnabled(False)
        self.actionPeak_Detection.setObjectName("actionPeak_Detection")
        self.actionRise_Time = QtWidgets.QAction(Analysis)
        self.actionRise_Time.setEnabled(False)
        self.actionRise_Time.setObjectName("actionRise_Time")
        self.actionFall_Time = QtWidgets.QAction(Analysis)
        self.actionFall_Time.setEnabled(False)
        self.actionFall_Time.setObjectName("actionFall_Time")
        self.actionFWHM = QtWidgets.QAction(Analysis)
        self.actionFWHM.setEnabled(False)
        self.actionFWHM.setObjectName("actionFWHM")
        self.actionX_Y = QtWidgets.QAction(Analysis)
        self.actionX_Y.setObjectName("actionX_Y")
        self.actionRadar_Plot = QtWidgets.QAction(Analysis)
        self.actionRadar_Plot.setObjectName("actionRadar_Plot")
        self.actionBox_Plot = QtWidgets.QAction(Analysis)
        self.actionBox_Plot.setObjectName("actionBox_Plot")
        self.menuNormalization.addAction(self.actionMax_min)
        self.menuNormalization.addAction(self.actionStandardization_M_0_S_1)
        self.menuMenu.addAction(self.actionOpen)
        self.menuMenu.addAction(self.menuNormalization.menuAction())
        self.menuMenu.addAction(self.actionBaseline_Correction)
        self.menuMenu.addAction(self.actionPeak_Detection)
        self.menuMenu.addAction(self.actionRise_Time)
        self.menuMenu.addAction(self.actionFall_Time)
        self.menuMenu.addAction(self.actionFWHM)
        self.menuPlots.addAction(self.actionX_Y)
        self.menuPlots.addAction(self.actionRadar_Plot)
        self.menuPlots.addAction(self.actionBox_Plot)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuPlots.menuAction())

        self.retranslateUi(Analysis)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Analysis)

    def retranslateUi(self, Analysis):
        _translate = QtCore.QCoreApplication.translate
        Analysis.setWindowTitle(_translate("Analysis", "Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Table), _translate("Analysis", "File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_XY), _translate("Analysis", "X-Y Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Radar), _translate("Analysis", "Radar Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Box), _translate("Analysis", "Box Plot"))
        self.menuMenu.setTitle(_translate("Analysis", "Menu"))
        self.menuNormalization.setTitle(_translate("Analysis", "Normalization"))
        self.menuPlots.setTitle(_translate("Analysis", "Plots"))
        self.actionOpen.setText(_translate("Analysis", "Open"))
        self.actionMax_min.setText(_translate("Analysis", "Max-min"))
        self.actionStandardization_M_0_S_1.setText(_translate("Analysis", "Standardization (M=0,S=1)"))
        self.actionBaseline_Correction.setText(_translate("Analysis", "Baseline Correction"))
        self.actionPeak_Detection.setText(_translate("Analysis", "Peak Detection"))
        self.actionRise_Time.setText(_translate("Analysis", "Rise Time"))
        self.actionFall_Time.setText(_translate("Analysis", "Fall Time"))
        self.actionFWHM.setText(_translate("Analysis", "FWHM"))
        self.actionX_Y.setText(_translate("Analysis", "X-Y"))
        self.actionRadar_Plot.setText(_translate("Analysis", "Radar Plot"))
        self.actionBox_Plot.setText(_translate("Analysis", "Box Plot"))

'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Analysis = QtWidgets.QMainWindow()
    ui = Ui_Analysis()
    ui.setupUi(Analysis)
    Analysis.show()
    sys.exit(app.exec_())
'''
